name: CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.4.0
      - uses: sdkman/sdkman-action@v1-preview-2
        with:
          candidate: java
          version: 11.0.17-amzn
      - uses: sdkman/sdkman-action@v1-preview-2
        with:
          candidate: jbake
          version: 2.6.6
      - name: Run JBake
        run: jbake -b
      - name: Copying API docs
        run: cp -r api output
      - name: Preview Results
        run: ls -lR output
