name: CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.4.0
      - name: Setup Java
        uses: actions/setup-java@v3.10.0
        with:
          java-version: '11'
          distribution: 'corretto'
      - name: Install Sdkman
        run: curl -s "https://get.sdkman.io" | bash
      - name: Install JBake
        run: sdk install jbake
      - name: Run JBake
        run: jbake -b
      - name: Copying API docs
        run: cp -r api output
      - name: Preview Results
        run: ls -lR output
